/**
 * Assignatura 21742 - Compiladors
 * Estudis: Grau en Informàtica
 * Itinerari: Computació
 * Curs: 2025-2026
 *
 * Professor: Pere Palmer
 *
 * Generar:
 * java -jar java-cup-11b.jar -expect 22 -parser Parser -symbols ParserSym -destdir gen src/gramatica/Parser.cup
 */
import java_cup.runtime.*;
import symbols.*;

import java.util.*;

class Parser;

parser code {:
    private int line(java_cup.runtime.Symbol s) {
        if(s == null) return safeLine(s);
        return s.left;
    }

    private int column(java_cup.runtime.Symbol s) {
        if (s == null) return safeColumn(s);
        return s.right;
    }

    private int safeLine(Symbol s) {
        return (s != null && s.left >= 0) ? s.left : 0;
    }

    private int safeColumn(Symbol s) {
        return (s != null && s.right >= 0) ? s.right : 0;
    }


    public <T> List<T> combinar(T first, List<T> rest) {
        List<T> list = new ArrayList<>();
        list.add(first);
        if (rest != null) list.addAll(rest);
        return list;
    }

    public <T> List<T> crearLlista(T item) {
        List<T> list = new ArrayList<>();
        list.add(item);
        return list;
    }

    public static SymbolTable currentScope = new SymbolTable(null);
:}

terminal Symbol
            PRINCIPAL, ENDPRINCIPAL,
            OP_IF, OP_THEN, OP_ELSE, OP_ENDIF,
            OP_SWITCH, DEFAULT_SWITCH, OP_ENDSWITCH,
            OP_WHILE, OP_DO, OP_ENDWHILE,
            OP_REP, PROCEDIMENT, ENDPROCEDIMENT,
            FUNCIO, ENDFUNCIO, TORNAR, CONST,
            OP_TIPUS_CADENA, OP_TIPUS_TUPLA,
            OP_TIPUS_ENTER, OP_TIPUS_LOGIC,
            PLUS, MINUS, TIMES, DIVIDE,
            EQ, NE, LT, LE, GT, GE, INPUT, OUTPUT,
            AND, OR, NOT, ASSIGNACIO, OBR_PAR,
            TANC_PAR, OBR_CORX, TANC_CORX, DOS_PUNTS,
            COMA, PUNT_COMA, COMENTARI, ERROR;

terminal String ID, CADENA;
terminal Double ENTER;
terminal Boolean VALOR_LOGIC;

non terminal ProgramNode program;
non terminal List<DeclNode> decls;
non terminal List<MethodNode> methods;
non terminal List<InstrNode> instrs, optional_cond;
non terminal DeclNode decl;
non terminal InstrNode instr,  entrada, sortida;
non terminal InstrNode.CallNode call;
non terminal CondNode cond;
non terminal CondNode.SwitchNode.CaseNode cas_opcio;
non terminal LoopNode loop;
non terminal MethodNode method;
non terminal TypeNode tipus, tupla_def;
non terminal ExprNode assig, expr, terme;
non terminal ArgNode arg;
non terminal List<ArgNode> args, tupla_camp_list;
non terminal List<CondNode.SwitchNode.CaseNode> cas_opcions;
non terminal String op_arit, op_rel, op_log;
non terminal List<ExprNode.VarNode> list_id;

// Associativitat i precedència dels operadors
precedence left OR;            // OR més baix que AND
precedence left AND;           // AND més baix que comparacions

precedence nonassoc EQ, NE, LT, LE, GT, GE;   // comparadors no associatius

precedence left PLUS, MINUS;    // suma i resta associatius a l'esquerra
precedence left TIMES, DIVIDE;  // multiplicació i divisió associatius a l'esquerra

precedence right NOT;          // negació (NOT) té associativitat a la dreta

start with program;

program ::= PRINCIPAL:p ID:id DOS_PUNTS decls:d methods:m instrs:i ENDPRINCIPAL
            {:
                RESULT = new ProgramNode(id, d, m, i, line(p), column(p));
            :}
;

decls ::= decl:d decls:ds
            {:
                RESULT = combinar(d, ds);
            :}
        | /* buit */
            {:
                RESULT = new ArrayList<DeclNode>();
            :}
;

decl ::= tipus:t list_id:l assig:a
            {:
                DeclNode d = new DeclNode(false, t, l, a);
                for(ExprNode.VarNode var : l) {
                    Simbol s = new Simbol(var.name, d.type, d.isConst, var.line, var.column);

                    if (!currentScope.add(s)) {
                        ErrorManager.add(new CompilerError(var.line, var.column, CompilerError.TYPE.SEMANTIC,
                            "Variable ja declarada: " + var.name));
                    }
                }
                RESULT = d;
            :}
        | CONST:c tipus:t list_id:l ASSIGNACIO expr:e
            {:
                DeclNode d = new DeclNode(true, t, l, e, line(c), column(c));
                for(ExprNode.VarNode var : l) {
                    Simbol s = new Simbol(var.name, d.type, d.isConst, var.line, var.column);

                    if (!currentScope.add(s)) {
                        ErrorManager.add(new CompilerError(var.line, var.column, CompilerError.TYPE.SEMANTIC,
                            "Constant ja declarada: " + var.name));
                    }
                }
                RESULT = d;
            :}
;

methods ::= method:m methods:ms
            {:
                RESULT = combinar(m, ms);
            :}
        | /* buit */
            {:
                RESULT = new ArrayList<MethodNode>();
            :}
;

method ::= FUNCIO:f tipus:t ID:id OBR_PAR args:a TANC_PAR DOS_PUNTS decls:d instrs:i TORNAR expr:e ENDFUNCIO
            {:
                SymbolTable oldScope = currentScope;
                currentScope = new SymbolTable(oldScope);

                Simbol s = new Simbol(id, t, false, Simbol.Methods.FUNCIO, line(f), column(f));

                MethodNode m = new MethodNode(true, id, t, a, d, i, e, line(f), column(f), currentScope);

                if (!currentScope.add(s)) {
                    ErrorManager.add(new CompilerError(line(f), column(f), CompilerError.TYPE.SEMANTIC,
                        "Nom ja utilitzat: " + id));
                }

                currentScope = oldScope;

                RESULT = m;
            :}
        | PROCEDIMENT:p ID:id OBR_PAR args:a TANC_PAR DOS_PUNTS decls:d instrs:i ENDPROCEDIMENT
            {:
                SymbolTable oldScope = currentScope;
                currentScope = new SymbolTable(oldScope);

                Simbol s = new Simbol(id, null, false, Simbol.Methods.PROCEDIMENT, line(p), column(p));

                MethodNode m = new MethodNode(true, id, null, a, d, i, null, line(p), column(p), currentScope);

                if (!currentScope.add(s)) {
                    ErrorManager.add(new CompilerError(line(p), column(p), CompilerError.TYPE.SEMANTIC,
                        "Nom ja utilitzat: " + id));
                }

                currentScope = oldScope;

                RESULT = m;
            :}
;

instrs ::= instr:i PUNT_COMA instrs:is
            {:
                RESULT = combinar(i, is);
            :}
        | /* buit */
            {:
                RESULT = new ArrayList<InstrNode>();
            :}
;

instr ::= call:c
            {:
                RESULT = c;
            :}
        | cond:c
            {:
                RESULT = c;
            :}
        | loop:l
            {:
                RESULT = l;
            :}
        | entrada:e
            {:
                RESULT = e;
            :}
        | sortida:s
            {:
                RESULT = s;
            :}
        | decl:d
            {:
                RESULT = new InstrNode.InstrDeclNode(d);
            :}
;

call ::= ID:id OBR_PAR args:a TANC_PAR
            {:
                RESULT = new InstrNode.CallNode(id, a);
            :}
;

cond ::= OP_IF:op OBR_PAR expr:e TANC_PAR OP_THEN instrs:i optional_cond:o
            {:
                RESULT = new CondNode.IfNode(e, i, o, line(op), column(op));
            :}
        | OP_SWITCH:s ID:id DOS_PUNTS cas_opcions:c DEFAULT_SWITCH DOS_PUNTS instrs:i OP_ENDSWITCH
            {:
                RESULT = new CondNode.SwitchNode(id, c, i, line(s), column(s));
            :}
;

optional_cond ::= OP_ELSE instrs:i OP_ENDIF
            {:
                RESULT = i;
            :}
        | OP_ENDIF
            {:
                RESULT = null;
            :}
;

cas_opcions ::= cas_opcio:c cas_opcions:cs
            {:
                RESULT = combinar(c, cs);
            :}
        | cas_opcio:c
            {:
                RESULT = crearLlista(c);
            :}
;

cas_opcio ::= terme:t DOS_PUNTS instrs:i
            {:
                RESULT = new CondNode.SwitchNode.CaseNode(t, i);
            :}
;

loop ::= OP_WHILE:w OBR_PAR expr:e TANC_PAR OP_DO instrs:i OP_ENDWHILE
            {:
                RESULT = new LoopNode.WhileNode(e, i, line(w), column(w));
            :}
        | OP_DO:d instrs:i OP_REP OBR_PAR expr:e TANC_PAR
            {:
                RESULT = new LoopNode.DoWhileNode(i, e, line(d), column(d));
            :}
;

entrada ::= INPUT:i OBR_PAR ID:id TANC_PAR
            {:
                RESULT = new InstrNode.InputNode(id, line(i), column(i));
            :}
;

sortida ::= OUTPUT:o OBR_PAR expr:e TANC_PAR
            {:
                RESULT = new InstrNode.OutputNode(e, line(o), column(o));
            :}
;

tipus ::= OP_TIPUS_ENTER:op
            {:
                RESULT = new TypeNode(TypeNode.Kind.INT, line(op), column(op));
            :}
        | OP_TIPUS_CADENA:op
            {:
                RESULT = new TypeNode(TypeNode.Kind.STRING, line(op), column(op));
            :}
        | OP_TIPUS_LOGIC:op
            {:
                RESULT = new TypeNode(TypeNode.Kind.BOOL, line(op), column(op));
            :}
        | OP_TIPUS_TUPLA tupla_def:td
            {:
                RESULT = td;
            :}
;

tupla_def ::= OBR_PAR:o tupla_camp_list:tcl TANC_PAR
            {:
                RESULT = new TypeNode(tcl, line(o), column(o));
            :}
;

tupla_camp_list ::= arg:a COMA tupla_camp_list:tcl
            {:
                RESULT = combinar(a, tcl);
            :}
        | arg:a
            {:
                RESULT = crearLlista(a);
            :}
;

list_id ::= ID:id COMA list_id:l
            {:
                RESULT = combinar(new ExprNode.VarNode(id), l);
            :}
        | ID:id
            {:
                RESULT = crearLlista(new ExprNode.VarNode(id));
            :}
;

args ::= arg:a COMA args:as
            {:
                RESULT = combinar(a, as);
            :}
        | arg: a
            {:
                RESULT = crearLlista(a);
            :}
        | /* buit */
            {:
                RESULT = new ArrayList<ArgNode>();
            :}
;

arg ::= ID:id DOS_PUNTS tipus:t
            {:
                RESULT = new ArgNode(new ExprNode.VarNode(id), t);
            :}
;

assig ::= ASSIGNACIO expr:e
            {:
                RESULT = e;
            :}
        | /* buit */
            {:
                RESULT = null;
            :}
;

expr ::= expr:e op_arit:op terme:t
            {:
                RESULT = new ExprNode.BinaryOpNode(e, op, t);
            :}
        | expr:e op_rel:op terme:t
            {:
                RESULT = new ExprNode.BinaryOpNode(e, op, t);
            :}
        | expr:e op_log:op terme:t
            {:
                RESULT = new ExprNode.BinaryOpNode(e, op, t);
            :}
        | OBR_PAR expr:e TANC_PAR
            {:
                RESULT = e;
            :}
        | NOT:n expr:e
            {:
                RESULT = new ExprNode.UnaryOpNode("NOT", e, line(n), column(n));
            :}
        | terme:t
            {:
                RESULT = t;
            :}
;

terme ::= VALOR_LOGIC:vl
            {:
                RESULT = new ExprNode.LiteralNode(vl);
            :}
        | ENTER:e
            {:
                RESULT = new ExprNode.LiteralNode(e);
            :}
        | ID:i
            {:
                RESULT = new ExprNode.VarNode(i);
            :}
        | CADENA:c
            {:
                RESULT = new ExprNode.LiteralNode(c);
            :}
        | call:c
            {:
                RESULT = new ExprNode.ExprInstrNode(c);
            :}
;

op_arit ::= PLUS
            {: RESULT = "+"; :}
        | MINUS
            {: RESULT = "-"; :}
        | TIMES
            {: RESULT = "*"; :}
        | DIVIDE
            {: RESULT = "/"; :}
;

op_rel ::= EQ
            {: RESULT = "=="; :}
        | NE
            {: RESULT = "!="; :}
        | LT
            {: RESULT = "<"; :}
        | LE
            {: RESULT = "<="; :}
        | GT
            {: RESULT = ">"; :}
        | GE
            {: RESULT = ">="; :}
;

op_log ::= AND
            {: RESULT = "i"; :}
        | OR
            {: RESULT = "o"; :}
;










