
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package frontend.parser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int TYPE_ID = 53;
  public static final int ENTER = 56;
  public static final int DIVIDE = 29;
  public static final int OP_REP = 15;
  public static final int OP_ENDWHILE = 14;
  public static final int DOS_PUNTS = 47;
  public static final int ENDPROCEDIMENT = 17;
  public static final int ASSIGNACIO = 42;
  public static final int CONST = 21;
  public static final int GE = 36;
  public static final int OUTPUT = 38;
  public static final int OP_ENDIF = 7;
  public static final int ENDFUNCIO = 19;
  public static final int INPUT = 37;
  public static final int OP_WHILE = 12;
  public static final int OP_ELSE = 6;
  public static final int OP_DO = 13;
  public static final int TANC_CLAU = 46;
  public static final int OBR_CLAU = 45;
  public static final int OP_THEN = 5;
  public static final int TORNAR = 20;
  public static final int PRINCIPAL = 2;
  public static final int NOT = 41;
  public static final int AND = 39;
  public static final int MENYS = 30;
  public static final int LT = 33;
  public static final int TANC_PAR = 44;
  public static final int CARACTER = 55;
  public static final int OR = 40;
  public static final int FI = 51;
  public static final int PROCEDIMENT = 16;
  public static final int PLUS = 27;
  public static final int FUNCIO = 18;
  public static final int ID = 52;
  public static final int OBR_PAR = 43;
  public static final int LE = 34;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int OP_ENDSWITCH = 11;
  public static final int OP_TIPUS_CADENA = 22;
  public static final int COMA = 48;
  public static final int CADENA = 54;
  public static final int DEFAULT_SWITCH = 10;
  public static final int OP_TIPUS_LOGIC = 26;
  public static final int EQ = 31;
  public static final int OP_CASE = 9;
  public static final int PUNT = 49;
  public static final int ENDPRINCIPAL = 3;
  public static final int OP_IF = 4;
  public static final int TIMES = 28;
  public static final int OP_TIPUS_ENTER = 25;
  public static final int VALOR_LOGIC = 57;
  public static final int OP_SWITCH = 8;
  public static final int NE = 32;
  public static final int OP_TIPUS_TUPLA = 23;
  public static final int GT = 35;
  public static final int INICI = 50;
  public static final int OP_TIPUS_CARACTER = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PRINCIPAL",
  "ENDPRINCIPAL",
  "OP_IF",
  "OP_THEN",
  "OP_ELSE",
  "OP_ENDIF",
  "OP_SWITCH",
  "OP_CASE",
  "DEFAULT_SWITCH",
  "OP_ENDSWITCH",
  "OP_WHILE",
  "OP_DO",
  "OP_ENDWHILE",
  "OP_REP",
  "PROCEDIMENT",
  "ENDPROCEDIMENT",
  "FUNCIO",
  "ENDFUNCIO",
  "TORNAR",
  "CONST",
  "OP_TIPUS_CADENA",
  "OP_TIPUS_TUPLA",
  "OP_TIPUS_CARACTER",
  "OP_TIPUS_ENTER",
  "OP_TIPUS_LOGIC",
  "PLUS",
  "TIMES",
  "DIVIDE",
  "MENYS",
  "EQ",
  "NE",
  "LT",
  "LE",
  "GT",
  "GE",
  "INPUT",
  "OUTPUT",
  "AND",
  "OR",
  "NOT",
  "ASSIGNACIO",
  "OBR_PAR",
  "TANC_PAR",
  "OBR_CLAU",
  "TANC_CLAU",
  "DOS_PUNTS",
  "COMA",
  "PUNT",
  "INICI",
  "FI",
  "ID",
  "TYPE_ID",
  "CADENA",
  "CARACTER",
  "ENTER",
  "VALOR_LOGIC"
  };
}

