// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/frontend/grammar/Lexer.flex

/**
 * Assignatura 21780 Compiladors
 * Estudis de Grau en Informàtica
 * Professor: Pere Palmer
 *
 * Compilació:
 * java -jar jflex-full-1.9.1.jar -d src/frontend/lexer src/frontend/grammar/Lexer.flex
 */
package frontend.lexer;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.*;

import frontend.parser.ParserSym;

import java_cup.runtime.*;

import errors.ErrorManager;
import errors.CompilerError;

@SuppressWarnings("fallthrough")
public class AnaLex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\1\4"+
    "\1\5\1\6\3\0\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\12\12\17\1\20\1\0\1\21"+
    "\1\22\1\21\2\0\4\23\1\24\25\23\1\0\1\25"+
    "\2\0\1\23\1\0\1\26\1\23\1\27\1\30\1\31"+
    "\1\32\1\33\1\23\1\34\2\23\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\4\23\1\50\1\0\1\51\7\0\1\3\u01a2\0\2\3"+
    "\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\4\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\5\14\1\15\3\14"+
    "\1\15\5\14\1\16\1\17\1\13\1\0\1\20\1\2"+
    "\4\0\1\21\10\14\1\22\13\14\1\23\3\14\1\24"+
    "\1\11\1\0\1\11\3\14\1\25\5\14\1\26\4\14"+
    "\1\27\20\14\1\30\3\14\1\31\13\14\1\32\1\14"+
    "\1\33\3\14\1\34\2\14\1\35\1\36\6\14\1\37"+
    "\1\14\1\40\6\14\1\41\1\42\6\14\1\43\1\14"+
    "\1\44\4\14\1\45\1\14\1\46\2\14\1\47\1\14"+
    "\1\50\2\14\1\51\1\52\1\53\1\54\6\14\1\55"+
    "\2\14\1\56\2\14\1\57\1\14\1\60";

  private static int [] zzUnpackAction() {
    int [] result = new int[187];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\250\0\322\0\374\0\52"+
    "\0\52\0\52\0\52\0\52\0\52\0\u0126\0\u0150\0\176"+
    "\0\u017a\0\u01a4\0\u01ce\0\u01f8\0\u0222\0\u024c\0\u0276\0\u02a0"+
    "\0\u02ca\0\u017a\0\u02f4\0\u031e\0\u0348\0\u0372\0\u039c\0\52"+
    "\0\52\0\52\0\250\0\52\0\u03c6\0\u03f0\0\u041a\0\u0444"+
    "\0\u046e\0\52\0\u0498\0\u04c2\0\u04ec\0\u0516\0\u0540\0\u056a"+
    "\0\u0594\0\u05be\0\u05e8\0\u0612\0\u063c\0\u0666\0\u0690\0\u06ba"+
    "\0\u06e4\0\u070e\0\u0738\0\u0762\0\u078c\0\u07b6\0\u07e0\0\u080a"+
    "\0\u0834\0\u085e\0\52\0\u0888\0\u08b2\0\u08b2\0\u08dc\0\u0906"+
    "\0\u0930\0\u017a\0\u095a\0\u0984\0\u09ae\0\u09d8\0\u0a02\0\u017a"+
    "\0\u0a2c\0\u0a56\0\u0a80\0\u0aaa\0\u017a\0\u0ad4\0\u0afe\0\u0b28"+
    "\0\u0b52\0\u0b7c\0\u0ba6\0\u0bd0\0\u0bfa\0\u0c24\0\u0c4e\0\u0c78"+
    "\0\u0ca2\0\u0ccc\0\u0cf6\0\u0d20\0\u0d4a\0\u017a\0\u0d74\0\u0d9e"+
    "\0\u0dc8\0\u017a\0\u0df2\0\u0e1c\0\u0e46\0\u0e70\0\u0e9a\0\u0ec4"+
    "\0\u0eee\0\u0f18\0\u0f42\0\u0f6c\0\u0f96\0\u017a\0\u0fc0\0\u017a"+
    "\0\u0fea\0\u1014\0\u103e\0\u017a\0\u1068\0\u1092\0\u017a\0\u017a"+
    "\0\u10bc\0\u10e6\0\u1110\0\u113a\0\u1164\0\u118e\0\u017a\0\u11b8"+
    "\0\u017a\0\u11e2\0\u120c\0\u1236\0\u1260\0\u128a\0\u12b4\0\u017a"+
    "\0\u017a\0\u12de\0\u1308\0\u1332\0\u135c\0\u1386\0\u13b0\0\u017a"+
    "\0\u13da\0\u017a\0\u1404\0\u142e\0\u1458\0\u1482\0\u017a\0\u14ac"+
    "\0\u017a\0\u14d6\0\u1500\0\u017a\0\u152a\0\u017a\0\u1554\0\u157e"+
    "\0\u017a\0\u017a\0\u017a\0\u017a\0\u15a8\0\u15d2\0\u15fc\0\u1626"+
    "\0\u1650\0\u167a\0\u017a\0\u16a4\0\u16ce\0\u017a\0\u16f8\0\u1722"+
    "\0\u017a\0\u174c\0\u017a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[187];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\2\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\4\2\21\1\2\1\22\1\23\1\21\1\24\1\25"+
    "\1\21\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\2\21\1\40\1\41\53\0\2\3"+
    "\71\0\1\42\27\0\5\43\1\44\44\43\6\0\1\45"+
    "\43\0\7\46\1\0\15\46\1\47\24\46\16\0\1\50"+
    "\1\16\4\0\1\51\4\0\1\51\42\0\1\52\46\0"+
    "\1\21\3\0\2\21\1\0\22\21\21\0\1\21\3\0"+
    "\2\21\1\0\7\21\1\53\12\21\21\0\1\21\3\0"+
    "\2\21\1\0\1\54\2\21\1\55\6\21\1\56\7\21"+
    "\21\0\1\21\3\0\2\21\1\0\11\21\1\57\10\21"+
    "\21\0\1\21\3\0\2\21\1\0\1\60\1\61\1\21"+
    "\1\62\2\21\1\63\1\21\1\64\2\21\1\65\2\21"+
    "\1\66\1\21\1\67\1\21\21\0\1\21\3\0\2\21"+
    "\1\0\11\21\1\70\10\21\21\0\1\21\3\0\2\21"+
    "\1\0\7\21\1\71\2\21\1\72\7\21\21\0\1\21"+
    "\3\0\2\21\1\0\3\21\1\73\16\21\21\0\1\21"+
    "\3\0\2\21\1\0\12\21\1\32\7\21\21\0\1\21"+
    "\3\0\2\21\1\0\15\21\1\74\4\21\21\0\1\21"+
    "\3\0\2\21\1\0\20\21\1\75\1\21\21\0\1\21"+
    "\3\0\2\21\1\0\3\21\1\76\16\21\21\0\1\21"+
    "\3\0\2\21\1\0\6\21\1\77\3\21\1\100\7\21"+
    "\21\0\1\21\3\0\2\21\1\0\12\21\1\101\5\21"+
    "\1\102\1\21\2\0\2\45\2\0\46\45\7\0\1\103"+
    "\42\0\2\46\2\0\46\46\17\0\1\104\45\0\1\105"+
    "\1\0\1\105\1\0\1\106\51\0\1\21\3\0\2\21"+
    "\1\0\17\21\1\107\2\21\21\0\1\21\3\0\2\21"+
    "\1\0\2\21\1\110\12\21\1\111\1\112\3\21\21\0"+
    "\1\21\3\0\2\21\1\0\15\21\1\113\4\21\21\0"+
    "\1\21\3\0\2\21\1\0\11\21\1\114\10\21\21\0"+
    "\1\21\3\0\2\21\1\0\17\21\1\115\2\21\21\0"+
    "\1\21\3\0\2\21\1\0\7\21\1\116\12\21\21\0"+
    "\1\21\3\0\2\21\1\0\1\117\21\21\21\0\1\21"+
    "\3\0\2\21\1\0\15\21\1\120\4\21\21\0\1\21"+
    "\3\0\2\21\1\0\4\21\1\121\6\21\1\122\6\21"+
    "\21\0\1\21\3\0\2\21\1\0\3\21\1\123\16\21"+
    "\21\0\1\21\3\0\2\21\1\0\15\21\1\124\4\21"+
    "\21\0\1\21\3\0\2\21\1\0\6\21\1\125\13\21"+
    "\21\0\1\21\3\0\2\21\1\0\11\21\1\126\10\21"+
    "\21\0\1\21\3\0\2\21\1\0\6\21\1\127\13\21"+
    "\21\0\1\21\3\0\2\21\1\0\1\130\21\21\21\0"+
    "\1\21\3\0\2\21\1\0\5\21\1\131\14\21\21\0"+
    "\1\21\3\0\2\21\1\0\11\21\1\132\10\21\21\0"+
    "\1\21\3\0\2\21\1\0\6\21\1\133\3\21\1\134"+
    "\7\21\21\0\1\21\3\0\2\21\1\0\1\135\21\21"+
    "\21\0\1\21\3\0\2\21\1\0\13\21\1\136\6\21"+
    "\21\0\1\21\3\0\2\21\1\0\11\21\1\137\10\21"+
    "\21\0\1\21\3\0\2\21\1\0\15\21\1\140\4\21"+
    "\21\0\1\21\3\0\2\21\1\0\15\21\1\141\4\21"+
    "\21\0\1\21\3\0\2\21\1\0\13\21\1\142\6\21"+
    "\21\0\1\104\4\0\1\51\4\0\1\51\37\0\1\106"+
    "\51\0\1\21\3\0\2\21\1\0\15\21\1\143\4\21"+
    "\21\0\1\21\3\0\2\21\1\0\3\21\1\144\16\21"+
    "\21\0\1\21\3\0\2\21\1\0\1\145\21\21\21\0"+
    "\1\21\3\0\2\21\1\0\17\21\1\146\2\21\21\0"+
    "\1\21\3\0\2\21\1\0\16\21\1\147\3\21\21\0"+
    "\1\21\3\0\2\21\1\0\3\21\1\150\11\21\1\151"+
    "\4\21\21\0\1\21\3\0\2\21\1\0\16\21\1\146"+
    "\3\21\21\0\1\21\3\0\2\21\1\0\16\21\1\152"+
    "\3\21\21\0\1\21\3\0\2\21\1\0\20\21\1\153"+
    "\1\21\21\0\1\21\3\0\2\21\1\0\15\21\1\154"+
    "\4\21\21\0\1\21\3\0\2\21\1\0\11\21\1\155"+
    "\10\21\21\0\1\21\3\0\2\21\1\0\6\21\1\156"+
    "\13\21\21\0\1\21\3\0\2\21\1\0\1\21\1\157"+
    "\20\21\21\0\1\21\3\0\2\21\1\0\1\21\1\160"+
    "\20\21\21\0\1\21\3\0\2\21\1\0\21\21\1\161"+
    "\21\0\1\21\3\0\2\21\1\0\6\21\1\162\13\21"+
    "\21\0\1\21\3\0\2\21\1\0\17\21\1\163\2\21"+
    "\21\0\1\21\3\0\2\21\1\0\11\21\1\164\10\21"+
    "\21\0\1\21\3\0\2\21\1\0\1\21\1\165\20\21"+
    "\21\0\1\21\3\0\2\21\1\0\11\21\1\166\10\21"+
    "\21\0\1\21\3\0\2\21\1\0\3\21\1\167\16\21"+
    "\21\0\1\21\3\0\2\21\1\0\12\21\1\170\7\21"+
    "\21\0\1\21\3\0\2\21\1\0\17\21\1\171\2\21"+
    "\21\0\1\21\3\0\2\21\1\0\11\21\1\172\10\21"+
    "\21\0\1\21\3\0\2\21\1\0\7\21\1\173\12\21"+
    "\21\0\1\21\3\0\2\21\1\0\3\21\1\174\16\21"+
    "\21\0\1\21\3\0\2\21\1\0\11\21\1\175\10\21"+
    "\21\0\1\21\3\0\2\21\1\0\1\21\1\176\20\21"+
    "\21\0\1\21\3\0\2\21\1\0\17\21\1\177\2\21"+
    "\21\0\1\21\3\0\2\21\1\0\15\21\1\200\4\21"+
    "\21\0\1\21\3\0\2\21\1\0\1\201\21\21\21\0"+
    "\1\21\3\0\2\21\1\0\11\21\1\202\10\21\21\0"+
    "\1\21\3\0\2\21\1\0\12\21\1\203\7\21\21\0"+
    "\1\21\3\0\2\21\1\0\17\21\1\204\2\21\21\0"+
    "\1\21\3\0\2\21\1\0\11\21\1\205\10\21\21\0"+
    "\1\21\3\0\2\21\1\0\6\21\1\206\13\21\21\0"+
    "\1\21\3\0\2\21\1\0\6\21\1\207\13\21\21\0"+
    "\1\21\3\0\2\21\1\0\12\21\1\210\7\21\21\0"+
    "\1\21\3\0\2\21\1\0\1\21\1\211\20\21\21\0"+
    "\1\21\3\0\2\21\1\0\15\21\1\212\4\21\21\0"+
    "\1\21\3\0\2\21\1\0\1\21\1\213\20\21\21\0"+
    "\1\21\3\0\2\21\1\0\3\21\1\214\16\21\21\0"+
    "\1\21\3\0\2\21\1\0\17\21\1\215\2\21\21\0"+
    "\1\21\3\0\2\21\1\0\6\21\1\216\13\21\21\0"+
    "\1\21\3\0\2\21\1\0\1\217\21\21\21\0\1\21"+
    "\3\0\2\21\1\0\1\220\21\21\21\0\1\21\3\0"+
    "\2\21\1\0\1\221\21\21\21\0\1\21\3\0\2\21"+
    "\1\0\17\21\1\222\2\21\21\0\1\21\3\0\2\21"+
    "\1\0\2\21\1\223\17\21\21\0\1\21\3\0\2\21"+
    "\1\0\1\21\1\224\20\21\21\0\1\21\3\0\2\21"+
    "\1\0\1\21\1\225\20\21\21\0\1\21\3\0\2\21"+
    "\1\0\15\21\1\226\4\21\21\0\1\21\3\0\2\21"+
    "\1\0\1\21\1\227\20\21\21\0\1\21\3\0\2\21"+
    "\1\0\12\21\1\230\7\21\21\0\1\21\3\0\2\21"+
    "\1\0\15\21\1\231\4\21\21\0\1\21\3\0\2\21"+
    "\1\0\3\21\1\232\16\21\21\0\1\21\3\0\2\21"+
    "\1\0\6\21\1\233\13\21\21\0\1\21\3\0\2\21"+
    "\1\0\2\21\1\234\17\21\21\0\1\21\3\0\2\21"+
    "\1\0\6\21\1\235\13\21\21\0\1\21\3\0\2\21"+
    "\1\0\2\21\1\236\17\21\21\0\1\21\3\0\2\21"+
    "\1\0\15\21\1\237\4\21\21\0\1\21\3\0\2\21"+
    "\1\0\3\21\1\240\16\21\21\0\1\21\3\0\2\21"+
    "\1\0\1\241\21\21\21\0\1\21\3\0\2\21\1\0"+
    "\6\21\1\242\13\21\21\0\1\21\3\0\2\21\1\0"+
    "\3\21\1\243\16\21\21\0\1\21\3\0\2\21\1\0"+
    "\3\21\1\244\16\21\21\0\1\21\3\0\2\21\1\0"+
    "\6\21\1\245\13\21\21\0\1\21\3\0\2\21\1\0"+
    "\16\21\1\246\3\21\21\0\1\21\3\0\2\21\1\0"+
    "\13\21\1\247\6\21\21\0\1\21\3\0\2\21\1\0"+
    "\6\21\1\250\13\21\21\0\1\21\3\0\2\21\1\0"+
    "\15\21\1\251\4\21\21\0\1\21\3\0\2\21\1\0"+
    "\1\252\21\21\21\0\1\21\3\0\2\21\1\0\15\21"+
    "\1\253\4\21\21\0\1\21\3\0\2\21\1\0\12\21"+
    "\1\254\7\21\21\0\1\21\3\0\2\21\1\0\2\21"+
    "\1\255\17\21\21\0\1\21\3\0\2\21\1\0\13\21"+
    "\1\256\6\21\21\0\1\21\3\0\2\21\1\0\1\257"+
    "\21\21\21\0\1\21\3\0\2\21\1\0\10\21\1\260"+
    "\11\21\21\0\1\21\3\0\2\21\1\0\6\21\1\261"+
    "\13\21\21\0\1\21\3\0\2\21\1\0\1\262\21\21"+
    "\21\0\1\21\3\0\2\21\1\0\7\21\1\263\12\21"+
    "\21\0\1\21\3\0\2\21\1\0\3\21\1\264\16\21"+
    "\21\0\1\21\3\0\2\21\1\0\10\21\1\265\11\21"+
    "\21\0\1\21\3\0\2\21\1\0\7\21\1\266\12\21"+
    "\21\0\1\21\3\0\2\21\1\0\11\21\1\267\10\21"+
    "\21\0\1\21\3\0\2\21\1\0\3\21\1\270\16\21"+
    "\21\0\1\21\3\0\2\21\1\0\17\21\1\271\2\21"+
    "\21\0\1\21\3\0\2\21\1\0\11\21\1\272\10\21"+
    "\21\0\1\21\3\0\2\21\1\0\17\21\1\273\2\21"+
    "\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[6006];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\6\11\22\1\3\11\1\0\1\11"+
    "\1\1\4\0\1\11\30\1\1\11\1\1\1\0\166\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[187];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  private final java.util.Set<String> userTypes = new java.util.HashSet<>();

  public void addUserType(String name) {
      userTypes.add(name);
  }


  private boolean isUserType(String name) {
      return userTypes.contains(name);
  }


  // ===== Dump de tokens =====
    private final StringBuilder tokenDump = new StringBuilder();
    private boolean headerPrinted = false;
    private int tokenIndex = 0;

    public String getTokenDump() {
        return tokenDump.toString();
    }

    private void logToken(Symbol s, String lexema) {
        if (!headerPrinted) {
            tokenDump.append("--- Fitxer de Tòkens ---\n\n");
            tokenDump.append(String.format(
                    " %3s | %-18s | %-10s | %-12s | %s%n",
                    "#", "token", "posició", "lexema", "valor"
            ));
            tokenDump.append(String.format(
                    " %3s-+-%-18s-+-%-10s-+-%-12s-+-%s%n",
                    "---", "------------------", "----------", "------------", "----------------"
            ));
            headerPrinted = true;
        }

        String tokenName;
        try {
            tokenName = (s.sym >= 0 && s.sym < ParserSym.terminalNames.length)
                    ? ParserSym.terminalNames[s.sym]
                    : ("#" + s.sym);
        } catch (Throwable t) {
            tokenName = "#" + s.sym;
        }

        String valueStr = (s.value == null) ? "-" : s.value.toString();
        String lexStr = (lexema == null || lexema.isEmpty()) ? "-" : lexema;

        tokenDump.append(String.format(
                " %3d | %-18s | %3d:%-6d | %-12s | %s%n",
                ++tokenIndex,
                tokenName,
                s.left, s.right,
                lexStr,
                valueStr
        ));
    }

    /** Sense atribut associat */
    private Symbol symbol(int type) {
        Symbol s = new Symbol(type);
        s.left = yyline + 1;        // línia (1-based)
        s.right = yycolumn + 1;     // columna (1-based)

        logToken(s, yytext());      // <-- AFEGIT
        return s;
    }

    /** Amb atribut associat */
    private Symbol symbol(int type, Object value) {
        Symbol s = new Symbol(type, value);
        s.left = yyline + 1;
        s.right = yycolumn + 1;

        logToken(s, yytext());      // <-- AFEGIT
        return s;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnaLex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {   return symbol(ParserSym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { ErrorManager.add(new CompilerError(
        yyline + 1, yycolumn + 1,
        CompilerError.TYPE.LEXIC,
        "Símbol desconegut: '" + yytext() + "'"
    ));

    return next_token();
            }
          // fall through
          case 49: break;
          case 2:
            { /* Ignorar */
            }
          // fall through
          case 50: break;
          case 3:
            { return symbol(ParserSym.OBR_PAR);
            }
          // fall through
          case 51: break;
          case 4:
            { return symbol(ParserSym.TANC_PAR);
            }
          // fall through
          case 52: break;
          case 5:
            { switch (yytext()) {
                              case "+" : return symbol(ParserSym.PLUS);
                              case "*" : return symbol(ParserSym.TIMES);
                              case "/" : return symbol(ParserSym.DIVIDE);
                          }
            }
          // fall through
          case 53: break;
          case 6:
            { return symbol(ParserSym.COMA);
            }
          // fall through
          case 54: break;
          case 7:
            { return symbol(ParserSym.MENYS);
            }
          // fall through
          case 55: break;
          case 8:
            { return symbol(ParserSym.PUNT);
            }
          // fall through
          case 56: break;
          case 9:
            { return symbol(ParserSym.ENTER, Double.parseDouble(this.yytext()));
            }
          // fall through
          case 57: break;
          case 10:
            { return symbol(ParserSym.DOS_PUNTS);
            }
          // fall through
          case 58: break;
          case 11:
            { switch (yytext()) {
                              case "=="  : return symbol(ParserSym.EQ);
                              case "!=" : return symbol(ParserSym.NE);
                              case "<"  : return symbol(ParserSym.LT);
                              case "<=" : return symbol(ParserSym.LE);
                              case ">"  : return symbol(ParserSym.GT);
                              case ">=" : return symbol(ParserSym.GE);
                          }
            }
          // fall through
          case 59: break;
          case 12:
            { String lex = yytext();
                        if (isUserType(lex)) return symbol(ParserSym.TYPE_ID, lex);
                        return symbol(ParserSym.ID, lex);
            }
          // fall through
          case 60: break;
          case 13:
            { switch (yytext()) {
                              case "i"  : return symbol(ParserSym.AND);
                              case "o"  : return symbol(ParserSym.OR);
                              case "no" : return symbol(ParserSym.NOT);
                          }
            }
          // fall through
          case 61: break;
          case 14:
            { return symbol(ParserSym.OBR_CLAU);
            }
          // fall through
          case 62: break;
          case 15:
            { return symbol(ParserSym.TANC_CLAU);
            }
          // fall through
          case 63: break;
          case 16:
            { String lexema = yytext();
                       // lleva les cometes
                       lexema = lexema.substring(1, lexema.length()-1);
                       return symbol(ParserSym.CADENA, lexema);
            }
          // fall through
          case 64: break;
          case 17:
            { return symbol(ParserSym.ASSIGNACIO);
            }
          // fall through
          case 65: break;
          case 18:
            { return symbol(ParserSym.FI);
            }
          // fall through
          case 66: break;
          case 19:
            { return symbol(ParserSym.OP_IF);
            }
          // fall through
          case 67: break;
          case 20:
            { String lexema = yytext();

                        lexema = lexema.substring(1, lexema.length() - 1);
                        char car;

                        if(lexema.length() == 1) {
                            car = lexema.charAt(0);
                        } else if (lexema.startsWith("\\")) {
                            // Seqüència escapada, com '\n', '\t', '\''
                            switch (lexema.charAt(1)) {
                                case 'n': car = '\n'; break;
                                case 't': car = '\t'; break;
                                case 'r': car = '\r'; break;
                                case '\'': car = '\''; break;
                                case '\\': car = '\\'; break;
                                default:
                                    throw new Error("Escape no reconegut: " + lexema);
                            }
                        } else {
                            throw new Error("Caràcter invàlid: " + lexema);
                        }

                        return symbol(ParserSym.CARACTER, car);
            }
          // fall through
          case 68: break;
          case 21:
            { return symbol(ParserSym.OP_SWITCH);
            }
          // fall through
          case 69: break;
          case 22:
            { return symbol(ParserSym.OP_DO);
            }
          // fall through
          case 70: break;
          case 23:
            { return symbol(ParserSym.OP_ENDIF);
            }
          // fall through
          case 71: break;
          case 24:
            { return symbol(ParserSym.VALOR_LOGIC, this.yytext().equals("cert"));
            }
          // fall through
          case 72: break;
          case 25:
            { return symbol(ParserSym.OP_ENDSWITCH);
            }
          // fall through
          case 73: break;
          case 26:
            { return symbol(ParserSym.OP_CASE);
            }
          // fall through
          case 74: break;
          case 27:
            { return symbol(ParserSym.OP_ELSE);
            }
          // fall through
          case 75: break;
          case 28:
            { return symbol(ParserSym.DEFAULT_SWITCH);
            }
          // fall through
          case 76: break;
          case 29:
            { return symbol(ParserSym.CONST);
            }
          // fall through
          case 77: break;
          case 30:
            { return symbol(ParserSym.OP_TIPUS_ENTER);
            }
          // fall through
          case 78: break;
          case 31:
            { return symbol(ParserSym.INICI);
            }
          // fall through
          case 79: break;
          case 32:
            { return symbol(ParserSym.OP_TIPUS_LOGIC);
            }
          // fall through
          case 80: break;
          case 33:
            { return symbol(ParserSym.OP_TIPUS_TUPLA);
            }
          // fall through
          case 81: break;
          case 34:
            { return symbol(ParserSym.OP_TIPUS_CADENA);
            }
          // fall through
          case 82: break;
          case 35:
            { return symbol(ParserSym.FUNCIO);
            }
          // fall through
          case 83: break;
          case 36:
            { return symbol(ParserSym.OP_WHILE);
            }
          // fall through
          case 84: break;
          case 37:
            { return symbol(ParserSym.TORNAR);
            }
          // fall through
          case 85: break;
          case 38:
            { return symbol(ParserSym.INPUT);
            }
          // fall through
          case 86: break;
          case 39:
            { return symbol(ParserSym.OP_ENDWHILE);
            }
          // fall through
          case 87: break;
          case 40:
            { return symbol(ParserSym.OP_THEN);
            }
          // fall through
          case 88: break;
          case 41:
            { return symbol(ParserSym.OP_REP);
            }
          // fall through
          case 89: break;
          case 42:
            { return symbol(ParserSym.OUTPUT);
            }
          // fall through
          case 90: break;
          case 43:
            { return symbol(ParserSym.OP_TIPUS_CARACTER);
            }
          // fall through
          case 91: break;
          case 44:
            { return symbol(ParserSym.ENDFUNCIO);
            }
          // fall through
          case 92: break;
          case 45:
            { return symbol(ParserSym.PRINCIPAL);
            }
          // fall through
          case 93: break;
          case 46:
            { return symbol(ParserSym.ENDPRINCIPAL);
            }
          // fall through
          case 94: break;
          case 47:
            { return symbol(ParserSym.PROCEDIMENT);
            }
          // fall through
          case 95: break;
          case 48:
            { return symbol(ParserSym.ENDPROCEDIMENT);
            }
          // fall through
          case 96: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
