// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/Lexer.flex

/**
 * Assignatura 21780 Compiladors
 * Estudis de Grau en Informàtica
 * Professor: Pere Palmer
 *
 * Compilació:
 */

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import token.TokenType;
import token.Yytoken.Nombre;
import token.Yytoken.TSimple;
import token.Yytoken.ValorLogic;
import token.Yytoken;

@SuppressWarnings("fallthrough")
public class AnaLex {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\1\4"+
    "\1\0\1\5\4\0\1\6\1\7\1\10\1\11\1\0"+
    "\1\11\1\12\1\10\12\13\1\14\1\0\1\15\1\16"+
    "\1\15\2\0\4\17\1\20\25\17\1\21\1\0\1\22"+
    "\1\0\1\17\1\0\1\23\1\17\1\24\1\25\1\26"+
    "\1\27\1\30\1\17\1\31\2\17\1\32\1\33\1\34"+
    "\1\35\1\36\1\17\1\37\1\40\1\41\1\42\1\43"+
    "\4\17\12\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\3\11\1\14\7\11"+
    "\1\10\1\15\2\0\1\16\16\11\1\17\2\11\1\6"+
    "\1\0\1\6\5\11\1\20\1\11\1\21\12\11\1\22"+
    "\11\11\1\23\3\11\1\24\1\25\3\11\1\26\4\11"+
    "\1\27\1\30\1\11\1\31\1\11\1\32\2\11\1\33"+
    "\1\34\1\35\1\11\1\36\3\11\1\37";

  private static int [] zzUnpackAction() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\44\0\110\0\154\0\220\0\44\0\44\0\44"+
    "\0\264\0\330\0\154\0\374\0\44\0\44\0\u0120\0\u0144"+
    "\0\u0168\0\374\0\u018c\0\u01b0\0\u01d4\0\u01f8\0\u021c\0\u0240"+
    "\0\u0264\0\44\0\u0288\0\u02ac\0\u02d0\0\44\0\u02f4\0\u0318"+
    "\0\u033c\0\u0360\0\u0384\0\u03a8\0\u03cc\0\u03f0\0\u0414\0\u0438"+
    "\0\u045c\0\u0480\0\u04a4\0\u04c8\0\u04ec\0\u0510\0\u0534\0\u0558"+
    "\0\u057c\0\u057c\0\u05a0\0\u05c4\0\u05e8\0\u060c\0\u0630\0\374"+
    "\0\u0654\0\374\0\u0678\0\u069c\0\u06c0\0\u06e4\0\u0708\0\u072c"+
    "\0\u0750\0\u0774\0\u0798\0\u07bc\0\374\0\u07e0\0\u0804\0\u0828"+
    "\0\u084c\0\u0870\0\u0894\0\u08b8\0\u08dc\0\u0900\0\374\0\u0924"+
    "\0\u0948\0\u096c\0\374\0\374\0\u0990\0\u09b4\0\u09d8\0\374"+
    "\0\u09fc\0\u0a20\0\u0a44\0\u0a68\0\374\0\374\0\u0a8c\0\374"+
    "\0\u0ab0\0\374\0\u0ad4\0\u0af8\0\374\0\374\0\374\0\u0b1c"+
    "\0\374\0\u0b40\0\u0b64\0\u0b88\0\374";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\2\10"+
    "\1\2\1\11\1\12\1\13\1\4\2\14\1\15\1\16"+
    "\1\14\1\17\1\14\1\20\1\21\1\14\1\22\1\23"+
    "\1\24\1\25\1\22\1\26\1\27\1\30\1\31\2\14"+
    "\45\0\2\3\57\0\1\32\32\0\1\33\50\0\1\34"+
    "\1\11\4\0\1\35\5\0\1\35\33\0\1\36\40\0"+
    "\1\14\3\0\2\14\2\0\21\14\13\0\1\14\3\0"+
    "\2\14\2\0\1\37\2\14\1\40\6\14\1\41\6\14"+
    "\13\0\1\14\3\0\2\14\2\0\11\14\1\42\7\14"+
    "\13\0\1\14\3\0\2\14\2\0\1\43\2\14\1\44"+
    "\4\14\1\45\4\14\1\46\1\14\1\47\1\14\13\0"+
    "\1\14\3\0\2\14\2\0\7\14\1\50\2\14\1\51"+
    "\6\14\13\0\1\14\3\0\2\14\2\0\3\14\1\52"+
    "\15\14\13\0\1\14\3\0\2\14\2\0\12\14\1\22"+
    "\6\14\13\0\1\14\3\0\2\14\2\0\14\14\1\53"+
    "\4\14\13\0\1\14\3\0\2\14\2\0\3\14\1\54"+
    "\15\14\13\0\1\14\3\0\2\14\2\0\6\14\1\55"+
    "\12\14\13\0\1\14\3\0\2\14\2\0\12\14\1\56"+
    "\4\14\1\57\1\14\2\33\2\0\40\33\13\0\1\60"+
    "\41\0\1\61\1\0\1\62\43\0\1\14\3\0\2\14"+
    "\2\0\2\14\1\63\16\14\13\0\1\14\3\0\2\14"+
    "\2\0\14\14\1\64\4\14\13\0\1\14\3\0\2\14"+
    "\2\0\11\14\1\65\7\14\13\0\1\14\3\0\2\14"+
    "\2\0\16\14\1\66\2\14\13\0\1\14\3\0\2\14"+
    "\2\0\7\14\1\67\11\14\13\0\1\14\3\0\2\14"+
    "\2\0\14\14\1\70\4\14\13\0\1\14\3\0\2\14"+
    "\2\0\3\14\1\71\15\14\13\0\1\14\3\0\2\14"+
    "\2\0\6\14\1\72\12\14\13\0\1\14\3\0\2\14"+
    "\2\0\11\14\1\73\7\14\13\0\1\14\3\0\2\14"+
    "\2\0\1\74\20\14\13\0\1\14\3\0\2\14\2\0"+
    "\5\14\1\75\13\14\13\0\1\14\3\0\2\14\2\0"+
    "\11\14\1\76\7\14\13\0\1\14\3\0\2\14\2\0"+
    "\12\14\1\77\6\14\13\0\1\14\3\0\2\14\2\0"+
    "\13\14\1\100\5\14\13\0\1\14\3\0\2\14\2\0"+
    "\11\14\1\101\7\14\13\0\1\14\3\0\2\14\2\0"+
    "\14\14\1\102\4\14\13\0\1\14\3\0\2\14\2\0"+
    "\13\14\1\103\5\14\13\0\1\60\4\0\1\35\5\0"+
    "\1\35\30\0\1\62\43\0\1\14\3\0\2\14\2\0"+
    "\3\14\1\104\15\14\13\0\1\14\3\0\2\14\2\0"+
    "\16\14\1\105\2\14\13\0\1\14\3\0\2\14\2\0"+
    "\15\14\1\106\3\14\13\0\1\14\3\0\2\14\2\0"+
    "\3\14\1\107\15\14\13\0\1\14\3\0\2\14\2\0"+
    "\15\14\1\105\3\14\13\0\1\14\3\0\2\14\2\0"+
    "\11\14\1\110\7\14\13\0\1\14\3\0\2\14\2\0"+
    "\1\14\1\111\17\14\13\0\1\14\3\0\2\14\2\0"+
    "\20\14\1\112\13\0\1\14\3\0\2\14\2\0\6\14"+
    "\1\113\12\14\13\0\1\14\3\0\2\14\2\0\16\14"+
    "\1\114\2\14\13\0\1\14\3\0\2\14\2\0\1\14"+
    "\1\115\17\14\13\0\1\14\3\0\2\14\2\0\3\14"+
    "\1\116\15\14\13\0\1\14\3\0\2\14\2\0\12\14"+
    "\1\117\6\14\13\0\1\14\3\0\2\14\2\0\11\14"+
    "\1\120\7\14\13\0\1\14\3\0\2\14\2\0\7\14"+
    "\1\121\11\14\13\0\1\14\3\0\2\14\2\0\11\14"+
    "\1\122\7\14\13\0\1\14\3\0\2\14\2\0\16\14"+
    "\1\123\2\14\13\0\1\14\3\0\2\14\2\0\14\14"+
    "\1\124\4\14\13\0\1\14\3\0\2\14\2\0\16\14"+
    "\1\125\2\14\13\0\1\14\3\0\2\14\2\0\6\14"+
    "\1\126\12\14\13\0\1\14\3\0\2\14\2\0\12\14"+
    "\1\127\6\14\13\0\1\14\3\0\2\14\2\0\1\14"+
    "\1\130\17\14\13\0\1\14\3\0\2\14\2\0\14\14"+
    "\1\131\4\14\13\0\1\14\3\0\2\14\2\0\3\14"+
    "\1\132\15\14\13\0\1\14\3\0\2\14\2\0\16\14"+
    "\1\133\2\14\13\0\1\14\3\0\2\14\2\0\1\134"+
    "\20\14\13\0\1\14\3\0\2\14\2\0\1\135\20\14"+
    "\13\0\1\14\3\0\2\14\2\0\1\136\20\14\13\0"+
    "\1\14\3\0\2\14\2\0\14\14\1\137\4\14\13\0"+
    "\1\14\3\0\2\14\2\0\12\14\1\140\6\14\13\0"+
    "\1\14\3\0\2\14\2\0\14\14\1\141\4\14\13\0"+
    "\1\14\3\0\2\14\2\0\3\14\1\142\15\14\13\0"+
    "\1\14\3\0\2\14\2\0\2\14\1\143\16\14\13\0"+
    "\1\14\3\0\2\14\2\0\6\14\1\144\12\14\13\0"+
    "\1\14\3\0\2\14\2\0\14\14\1\145\4\14\13\0"+
    "\1\14\3\0\2\14\2\0\3\14\1\146\15\14\13\0"+
    "\1\14\3\0\2\14\2\0\15\14\1\147\3\14\13\0"+
    "\1\14\3\0\2\14\2\0\6\14\1\150\12\14\13\0"+
    "\1\14\3\0\2\14\2\0\14\14\1\151\4\14\13\0"+
    "\1\14\3\0\2\14\2\0\10\14\1\152\10\14\13\0"+
    "\1\14\3\0\2\14\2\0\3\14\1\153\15\14\13\0"+
    "\1\14\3\0\2\14\2\0\11\14\1\154\7\14\13\0"+
    "\1\14\3\0\2\14\2\0\16\14\1\155\2\14";

  private static int [] zzUnpacktrans() {
    int [] result = new int[2988];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\3\11\4\1\2\11\13\1\1\11"+
    "\1\1\2\0\1\11\22\1\1\0\74\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    public static void main(String []args) {
       /* if (args.length < 1) {
            System.err.println("Indica un fitxer amb les dades d'entrada");
            System.exit(0);
        }*/
        try {
            FileReader in = new FileReader("src/valorsidproves.txt");
            AnaLex lexer = new AnaLex(in);
            Yytoken token;

            while((token = lexer.yylex()) != null) {
                System.out.println(token);
            }
        } catch (FileNotFoundException e) {
            System.err.println("El fitxer d'entrada no existeix");;
        } catch (IOException e) {
            System.err.println("Error processant el fitxer d'entrada");
        }
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnaLex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Yytoken yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new TSimple(TokenType.ERROR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 32: break;
          case 2:
            { /* Ignorar */
            }
          // fall through
          case 33: break;
          case 3:
            { return new Yytoken(TokenType.OBR_PAR, yyline, yycolumn);
            }
          // fall through
          case 34: break;
          case 4:
            { return new Yytoken(TokenType.TANC_PAR, yyline, yycolumn);
            }
          // fall through
          case 35: break;
          case 5:
            { switch (yytext()) {
                              case "+" : return new Yytoken(TokenType.PLUS, yyline, yycolumn);
                              case "-" : return new Yytoken(TokenType.MINUS, yyline, yycolumn);
                              case "*" : return new Yytoken(TokenType.TIMES, yyline, yycolumn);
                              case "/" : return new Yytoken(TokenType.DIVIDE, yyline, yycolumn);
                          }
            }
          // fall through
          case 36: break;
          case 6:
            { return new Nombre(Double.parseDouble(yytext()), yyline, yycolumn);
            }
          // fall through
          case 37: break;
          case 7:
            { return new Yytoken(TokenType.DOS_PUNTS, yyline, yycolumn);
            }
          // fall through
          case 38: break;
          case 8:
            { switch (yytext()) {
                              case "=="  : return new Yytoken(TokenType.EQ, yyline, yycolumn);
                              case "!=" : return new Yytoken(TokenType.NE, yyline, yycolumn);
                              case "<"  : return new Yytoken(TokenType.LT, yyline, yycolumn);
                              case "<=" : return new Yytoken(TokenType.LE, yyline, yycolumn);
                              case ">"  : return new Yytoken(TokenType.GT, yyline, yycolumn);
                              case ">=" : return new Yytoken(TokenType.GE, yyline, yycolumn);
                          }
            }
          // fall through
          case 39: break;
          case 9:
            { return new TSimple(TokenType.ID, yytext(), yyline, yycolumn);
            }
          // fall through
          case 40: break;
          case 10:
            { return new Yytoken(TokenType.OBR_CORX, yyline, yycolumn);
            }
          // fall through
          case 41: break;
          case 11:
            { return new Yytoken(TokenType.TANC_CORX, yyline, yycolumn);
            }
          // fall through
          case 42: break;
          case 12:
            { switch (yytext()) {
                              case "i"  : return new Yytoken(TokenType.AND, yyline, yycolumn);
                              case "o"  : return new Yytoken(TokenType.OR, yyline, yycolumn);
                              case "no" : return new Yytoken(TokenType.NOT, yyline, yycolumn);
                          }
            }
          // fall through
          case 43: break;
          case 13:
            { return new TSimple(TokenType.COMENTARI, yytext(), yyline, yycolumn);
            }
          // fall through
          case 44: break;
          case 14:
            { return new Yytoken(TokenType.ASSIGNACIO, yyline, yycolumn);
            }
          // fall through
          case 45: break;
          case 15:
            { return new Yytoken(TokenType.OP_IF, yyline, yycolumn);
            }
          // fall through
          case 46: break;
          case 16:
            { return new Yytoken(TokenType.OP_DO, yyline, yycolumn);
            }
          // fall through
          case 47: break;
          case 17:
            { return new Yytoken(TokenType.OP_ENDIF, yyline, yycolumn);
            }
          // fall through
          case 48: break;
          case 18:
            { return new ValorLogic(yytext().equals("cert"), yyline, yycolumn);
            }
          // fall through
          case 49: break;
          case 19:
            { return new Yytoken(TokenType.OP_ELSE, yyline, yycolumn);
            }
          // fall through
          case 50: break;
          case 20:
            { return new Yytoken(TokenType.CONST, yyline, yycolumn);
            }
          // fall through
          case 51: break;
          case 21:
            { return new Yytoken(TokenType.OP_TIPUS_ENTER, yyline, yycolumn);
            }
          // fall through
          case 52: break;
          case 22:
            { return new Yytoken(TokenType.OP_TIPUS_LOGIC, yyline, yycolumn);
            }
          // fall through
          case 53: break;
          case 23:
            { return new Yytoken(TokenType.OP_TIPUS_TUPLA, yyline, yycolumn);
            }
          // fall through
          case 54: break;
          case 24:
            { return new Yytoken(TokenType.OP_TIPUS_CADENA, yyline, yycolumn);
            }
          // fall through
          case 55: break;
          case 25:
            { return new Yytoken(TokenType.FUNCIO, yyline, yycolumn);
            }
          // fall through
          case 56: break;
          case 26:
            { return new Yytoken(TokenType.OP_WHILE, yyline, yycolumn);
            }
          // fall through
          case 57: break;
          case 27:
            { return new Yytoken(TokenType.TORNAR, yyline, yycolumn);
            }
          // fall through
          case 58: break;
          case 28:
            { return new Yytoken(TokenType.OP_ENDWHILE, yyline, yycolumn);
            }
          // fall through
          case 59: break;
          case 29:
            { return new Yytoken(TokenType.OP_THEN, yyline, yycolumn);
            }
          // fall through
          case 60: break;
          case 30:
            { return new Yytoken(TokenType.OP_REP, yyline, yycolumn);
            }
          // fall through
          case 61: break;
          case 31:
            { return new Yytoken(TokenType.PROCEDIMENT, yyline, yycolumn);
            }
          // fall through
          case 62: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
